service_name: travis-pro
repo_token: xeXTDXSQmBXLR5KNbi1DGw


[![Coverage Status](https://coveralls.io/repos/github/JustineRobert/Teamwork/badge.svg?branch=master)](https://coveralls.io/github/JustineRobert/Teamwork?branch=master)